# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95096340424239f449d15448371f57b003cfdc69c87ffefce09b869906a0f69dfe0d5518f6143d80a2132a89bb3325f7e1678992efdf1085bd78cff2069b3fc

test:
  secret_key_base: c511c940cb2f98ea45d87b57f4bbf3f7dde6c76d1ccac35b354e4b9f337e3d3a325ddf976bcc3caa143dc95819299bfdba0aaad7fa7b777a81621df8abb28db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
